### ISSUE TITLE
Missing dependencies: vue-demi (using pnpm)

### ISSUE THREAD

**Issue by martinussuherman** [lstoeferle/vite-vue2-example#1]
Dear @lstoeferle, I've tried to run your project locally but gets into problem.

Here are the steps of what I've done:
- git clone lstoeferle/vite-vue2-windicss-starter
- pnpm install
- pnpm run dev

Here are the error:
```
> vite-vue2-example@1.0.0 dev E:\Data\Projects\testing\vue-test\vite-vue2-windicss-starter
> vite

error when starting dev server:
Error: The following dependencies are imported but could not be resolved:

  vue-demi (imported by E:/Data/Projects/testing/vue-test/vite-vue2-windicss-starter/src/main.ts)

Are they installed?
    at optimizeDeps (E:\Data\Projects\testing\vue-test\vite-vue2-windicss-starter\node_modules\.pnpm\vite@2.0.3\node_modules\vite\dist\node\chunks\dep-00e79b84.js:67615:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async runOptimize (E:\Data\Projects\testing\vue-test\vite-vue2-windicss-starter\node_modules\.pnpm\vite@2.0.3\node_modules\vite\dist\node\chunks\dep-00e79b84.js:68170:48)
    at async Server.httpServer.listen (E:\Data\Projects\testing\vue-test\vite-vue2-windicss-starter\node_modules\.pnpm\vite@2.0.3\node_modules\vite\dist\node\chunks\dep-00e79b84.js:68184:17)
 ERROR  Command failed with exit code 1.
```

Looks like vue-demi is missing from package.json.

Regards,

Martinus

**Comment by lstoeferle** [comment]
Hey @martinussuherman,

I've never used `pnpm`, will give it a try. Normally the `vue-demi` dependency is provided by the `@vueuse/core` package.

Thanks for the hint 👍

Kind regards,
Lukas

**Comment by martinussuherman** [comment]
Well, I guess somehow with pnpm, vite can't find the implicit dependencies. Thanks for the info @lstoeferle.

Regards,

Martinus
